### PR TITLE
Adapt to math-comp/math-comp#1166

### PR DESCRIPTION
**Pull request by pi8027**
We plan to change the type of the display parameter of the order type structures in order.v (see math-comp/math-comp#1166). This PR provides a compatibility layer.

### CODE REVIEW

**Comment by proux01** [comment]
@arthuraa upstream PR in mathcomp is now ready for merge. This overlay being backward compatible, could you please merge it so that we can then merge the upstream PR.

**Comment by arthuraa** [comment]
@pi8027 @proux01 Sorry for the delay!

**Comment by arthuraa** [comment]
Hm, as far as I can tell, I merged this PR into master, but it is still being displayed as just "closed", rather than "merged"... Any idea about what might have happened?

**Comment by proux01** [comment]
> Sorry for the delay!

No worries, we are waiting for the upstream PR for maybe a year, so I wouldn't call a few hours a "delay".

> Hm, as far as I can tell, I merged this PR into master, but it is still being displayed as just "closed", rather than "merged"... Any idea about what might have happened?

I don't know, apparently some strange interaction with #27 . Anyway, the commits are there on master, that's what counts.

**Comment by pi8027** [comment]
> No worries, we are waiting for the upstream PR for maybe a year, so I wouldn't call a few hours a "delay".

Actually, I have been waiting for 4 years :-)

**Pull request closed without merging**
