### PR TITLE
Adapt w.r.t. coq/coq#16004.

### PR DESCRIPTION
**Pull request by ppedrot**

### CODE REVIEW

**Comment by ppedrot** [comment]
The 8.11 CI seems to die from an unrelated OOM now, in theory it should compile fine I think.

**Comment by ppedrot** [comment]
@arthuraa ping

**Comment by arthuraa** [comment]
Thanks for this! Sorry for the delay, it's a holiday weekend here. I'll
take care of it ASAP.

**Comment by ppedrot** [comment]
Thanks!

**Pull request merged**
